### ISSUE TITLE
go client blacklists only a single IP?

### ISSUE THREAD

**Issue by davehorton** [palner/apiban#1]
I've been using this on several systems for a while -- the iptables client, that is.  I noticed on the last 2 servers I have run it on it blacklists a very small list of IPs, as opposed to earlier when the list was quite long.

Am I doing something wrong?  Here's an example where I ran it on a fresh VM and it only blaclisted a single address.

```
sudo /usr/local/bin/apiban/apiban-iptables-client
root@ip-172-31-34-163:/home/admin# iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N APIBAN
-A INPUT -j APIBAN
-A FORWARD -j APIBAN
-A APIBAN -s 194.88.143.44/32 -j REJECT --reject-with icmp-port-unreachable
```

**Comment by fredposner** [comment]
I've just run some tests and am seeing a full pull when first run or by requesting a full pull (which is up to 250 addresses at a time). If you're copying over the config.json, please make sure you change the LKID value to "0" (which is the default and will run a full pull) or manually run a FULL pull via:

```apiban-iptables-client FULL```

It's recommended that each deployment use a unique apikey so as to not hit any rate-limits.

If this does not resolve your issue, can you please post the log output?

Thank you. I look forward to your response.

**Comment by davehorton** [comment]
I would agree with your suggestion about a unique api key.....but how?  Seems that right now an API key is tied to an email address, or am I missing something.

The usefulness of this API definitely is based on the ability to deploy it widespread.  If I can only put it on one or two servers its not that useful to me.

To that end, I am trying to sping iup an AMI that has the go client and crontab ready to go.  Interestingly, I copy a valid config.json into my AMI build, but once I spin up an instance the config.json on the instance it has transmogrified into this:

```
{
	"APIKEY":"12c2aunauthorized3e1ec7c467cunauthorized7ce3unauthorizedcab621734",
	"LKID":"unauthorized",
	"VERSION":"unauthorized.3"
}
```

**Comment by fredposner** [comment]
Each API Key needs a unique name and email... and widespread is the goal here and the apikey. If you have a case needing many apikeys, not a problem as we're here to help. Although the use may be outside the simple apirequest form, you can always contact me through the site (matrix or email is listed) and we can get some bulk keys as needed.

Is there a log corresponding to the above you can paste? I do see in our logs the key attempt. The original request came from `12c2a15844498813e1ec7c467c15844498817ce31584449881cab621734` which is not a valid apikey.

**Comment by davehorton** [comment]
Its interesting, I am trying to create an AMI image using packer, and I know that I am putting a valid api key into the image, yet when I boot up it has been modified as above.  Tried it twice.  I'll have to come back to this when I have more time.  Unfortunately will have to remove it for now.

**Comment by fredposner** [comment]
I see a possibility where if the LKID (last known ID) was perhaps in the APIKEY string that it could be replaced. Does this look like a possibility?

**Comment by davehorton** [comment]
Hmm, no I don't think so.  Redacting most of my key but this is the config.json I copy into the ami
```
{
	"APIKEY":"12c2a03XXXXXXXXXXX621734",
	"LKID":"0",
	"VERSION":"0.3"
}
```

**Comment by fredposner** [comment]
Didn't mean to close... can you test with the updated version? It changes how the LKID is replaced.

**Comment by davehorton** [comment]
will do

**Comment by fredposner** [comment]
Hi @davehorton ... any luck?

**Comment by fredposner** [comment]
Hi @davehorton , sorry to bother... any luck?

**Comment by fredposner** [comment]
@davehorton I believe this issue to be resolved. Closing. Please open a new issue if you have any problems and I thank you greatly for this submission.
